"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 09:11:48.188051
"""
from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticket_categories_id"), "ticket_categories", ["id"], unique=False)
    op.create_index(op.f("ix_ticket_categories_name"), "ticket_categories", ["name"], unique=True)
    op.create_table(
        "ticket_subcategories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("extra_fields_template", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["ticket_categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_subcategories_id"), "ticket_subcategories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_subcategories_name"), "ticket_subcategories", ["name"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("subcategory_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "ON_HOLD",
                "RESOLVED",
                "CLOSED",
                "CANCELLED",
                name="ticketstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "URGENT", name="ticketpriority"),
            nullable=True,
        ),
        sa.Column("urgency", sa.Enum("LOW", "MEDIUM", "HIGH", name="ticketurgency"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("reopen_count", sa.Integer(), nullable=True),
        sa.Column("last_reopened_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["ticket_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["ticket_subcategories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickets_created_at"), "tickets", ["created_at"], unique=False)
    op.create_index(op.f("ix_tickets_id"), "tickets", ["id"], unique=False)
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_index(op.f("ix_tickets_title"), "tickets", ["title"], unique=False)
    op.create_index(op.f("ix_tickets_user_id"), "tickets", ["user_id"], unique=False)
    op.create_table(
        "ticket_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_comments_created_at"), "ticket_comments", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_ticket_comments_id"), "ticket_comments", ["id"], unique=False)
    op.create_index(
        op.f("ix_ticket_comments_ticket_id"), "ticket_comments", ["ticket_id"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_comments_user_id"), "ticket_comments", ["user_id"], unique=False
    )
    op.create_table(
        "ticket_extra_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("subcategory_id", sa.Integer(), nullable=True),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("field_value", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["ticket_subcategories.id"],
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticket_extra_fields_id"), "ticket_extra_fields", ["id"], unique=False)
    op.create_table(
        "ticket_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("changed_by_id", sa.String(length=100), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("change_type", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_history_changed_by_id"), "ticket_history", ["changed_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_history_created_at"), "ticket_history", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_ticket_history_id"), "ticket_history", ["id"], unique=False)
    op.create_index(
        op.f("ix_ticket_history_ticket_id"), "ticket_history", ["ticket_id"], unique=False
    )
    op.create_table(
        "ticket_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_type", sa.String(length=50), nullable=True),
        sa.Column("uploaded_by_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["comment_id"], ["ticket_comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_attachments_created_at"), "ticket_attachments", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_ticket_attachments_id"), "ticket_attachments", ["id"], unique=False)
    op.create_index(
        op.f("ix_ticket_attachments_ticket_id"), "ticket_attachments", ["ticket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_attachments_ticket_id"), table_name="ticket_attachments")
    op.drop_index(op.f("ix_ticket_attachments_id"), table_name="ticket_attachments")
    op.drop_index(op.f("ix_ticket_attachments_created_at"), table_name="ticket_attachments")
    op.drop_table("ticket_attachments")
    op.drop_index(op.f("ix_ticket_history_ticket_id"), table_name="ticket_history")
    op.drop_index(op.f("ix_ticket_history_id"), table_name="ticket_history")
    op.drop_index(op.f("ix_ticket_history_created_at"), table_name="ticket_history")
    op.drop_index(op.f("ix_ticket_history_changed_by_id"), table_name="ticket_history")
    op.drop_table("ticket_history")
    op.drop_index(op.f("ix_ticket_extra_fields_id"), table_name="ticket_extra_fields")
    op.drop_table("ticket_extra_fields")
    op.drop_index(op.f("ix_ticket_comments_user_id"), table_name="ticket_comments")
    op.drop_index(op.f("ix_ticket_comments_ticket_id"), table_name="ticket_comments")
    op.drop_index(op.f("ix_ticket_comments_id"), table_name="ticket_comments")
    op.drop_index(op.f("ix_ticket_comments_created_at"), table_name="ticket_comments")
    op.drop_table("ticket_comments")
    op.drop_index(op.f("ix_tickets_user_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_title"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_created_at"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_ticket_subcategories_name"), table_name="ticket_subcategories")
    op.drop_index(op.f("ix_ticket_subcategories_id"), table_name="ticket_subcategories")
    op.drop_table("ticket_subcategories")
    op.drop_index(op.f("ix_ticket_categories_name"), table_name="ticket_categories")
    op.drop_index(op.f("ix_ticket_categories_id"), table_name="ticket_categories")
    op.drop_table("ticket_categories")
    # ### end Alembic commands ###
    bind = op.get_bind()
    for name in ("ticketstatus", "ticketpriority", "ticketurgency"):
        sa.Enum(name=name).drop(bind, checkfirst=True)
