"""assignment and sla

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 09:24:31.348989
"""
from alembic import op
import sqlalchemy as sa
from datetime import timedelta


revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("assigned_to_id", sa.String(length=100), nullable=True))
    op.add_column("tickets", sa.Column("assigned_at", sa.DateTime(), nullable=True))
    op.add_column("tickets", sa.Column("first_response_at", sa.DateTime(), nullable=True))
    op.add_column("tickets", sa.Column("sla_response_due", sa.DateTime(), nullable=True))
    op.add_column("tickets", sa.Column("sla_resolution_due", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_tickets_assigned_to_id"), "tickets", ["assigned_to_id"], unique=False)
    # ### end Alembic commands ###
    # Backfill SLA due dates for existing tickets using the default targets (24h / 72h).
    bind = op.get_bind()
    tickets = sa.table(
        "tickets",
        sa.column("id", sa.Integer),
        sa.column("created_at", sa.DateTime),
        sa.column("sla_response_due", sa.DateTime),
        sa.column("sla_resolution_due", sa.DateTime),
    )
    for row in bind.execute(sa.select(tickets.c.id, tickets.c.created_at)).fetchall():
        if row.created_at is None:
            continue
        bind.execute(
            tickets.update()
            .where(tickets.c.id == row.id)
            .values(
                sla_response_due=row.created_at + timedelta(hours=24),
                sla_resolution_due=row.created_at + timedelta(hours=72),
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_assigned_to_id"), table_name="tickets")
    op.drop_column("tickets", "sla_resolution_due")
    op.drop_column("tickets", "sla_response_due")
    op.drop_column("tickets", "first_response_at")
    op.drop_column("tickets", "assigned_at")
    op.drop_column("tickets", "assigned_to_id")
    # ### end Alembic commands ###
