"""phase 3 tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 00:42:26.791815
"""
from alembic import op
import sqlalchemy as sa


revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tags", sa.String(length=300), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["ticket_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kb_articles_id"), "kb_articles", ["id"], unique=False)
    op.create_index(op.f("ix_kb_articles_title"), "kb_articles", ["title"], unique=False)
    op.create_table(
        "sla_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("response_hours", sa.Integer(), nullable=False),
        sa.Column("resolution_hours", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["ticket_categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id"),
    )
    op.create_index(op.f("ix_sla_rules_id"), "sla_rules", ["id"], unique=False)
    op.create_table(
        "ticket_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_feedback_rating"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_id"),
    )
    op.create_table(
        "ticket_kb_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("linked_by_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_id", "article_id", name="uq_ticket_article"),
    )
    op.add_column(
        "ticket_subcategories",
        sa.Column(
            "requires_approval", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("tickets", sa.Column("approval_status", sa.String(length=20), nullable=True))
    op.add_column("tickets", sa.Column("approver_id", sa.String(length=100), nullable=True))
    op.add_column(
        "tickets", sa.Column("approval_decided_by_id", sa.String(length=100), nullable=True)
    )
    op.add_column("tickets", sa.Column("approval_decided_at", sa.DateTime(), nullable=True))
    op.add_column("tickets", sa.Column("approval_comment", sa.Text(), nullable=True))
    op.create_index(op.f("ix_tickets_approver_id"), "tickets", ["approver_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_approver_id"), table_name="tickets")
    op.drop_column("tickets", "approval_comment")
    op.drop_column("tickets", "approval_decided_at")
    op.drop_column("tickets", "approval_decided_by_id")
    op.drop_column("tickets", "approver_id")
    op.drop_column("tickets", "approval_status")
    op.drop_column("ticket_subcategories", "requires_approval")
    op.drop_table("ticket_kb_links")
    op.drop_table("ticket_feedback")
    op.drop_index(op.f("ix_sla_rules_id"), table_name="sla_rules")
    op.drop_table("sla_rules")
    op.drop_index(op.f("ix_kb_articles_title"), table_name="kb_articles")
    op.drop_index(op.f("ix_kb_articles_id"), table_name="kb_articles")
    op.drop_table("kb_articles")
    # ### end Alembic commands ###
